/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_joseluispereira;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author j0c3lwiz
 */
public class princi extends javax.swing.JFrame {

    /**
     * Creates new form princi
     */
    public princi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtap = new javax.swing.JTabbedPane();
        uno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sp_posibilidad_retraso = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sp_duracion = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre_projecto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        wombo_projecto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        wombo_tipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        projectos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_sucesoras = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        actividad_predecesoras = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_predecesoras = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_activs = new javax.swing.JTree();
        olawenas = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        wombo_hilo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtap.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtapStateChanged(evt);
            }
        });

        uno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Crear Actividades");

        jLabel2.setText("Nombre Actividad :");

        jLabel3.setText("Posibilidad de Retraso :");

        sp_posibilidad_retraso.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel4.setText("Duracion :");

        sp_duracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Crear Projecto");

        jLabel6.setText("Nombre Projecto");

        jButton1.setText("Crear Actividad");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Projecto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel9.setText("Projecto");

        wombo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principal", "Predecesora", "Sucesora" }));

        jLabel11.setText("Tipo");

        javax.swing.GroupLayout unoLayout = new javax.swing.GroupLayout(uno);
        uno.setLayout(unoLayout);
        unoLayout.setHorizontalGroup(
            unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(unoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(unoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(unoLayout.createSequentialGroup()
                        .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(21, 21, 21)
                        .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wombo_projecto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_posibilidad_retraso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wombo_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombre_projecto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(70, 70, 70))
        );
        unoLayout.setVerticalGroup(
            unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(75, 75, 75)
                .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wombo_projecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombre_projecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_posibilidad_retraso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wombo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(24, 24, 24))
        );

        jtap.addTab("Crear", uno);

        projectos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                projectosItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Seleccione la actividad");

        jl_sucesoras.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_sucesoras);

        jButton3.setText("Agregar ");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel7.setText("Projecto");

        jLabel10.setText("Principal");

        jLabel12.setText("Sucesora");

        jl_predecesoras.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_predecesoras);

        jLabel13.setText("Predecesora");

        jButton5.setText("Agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Finalizar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel14.setText("Calcular atributos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(actividad_predecesoras, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(projectos, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButton5)
                .addGap(224, 224, 224))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(projectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(actividad_predecesoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton5))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))))
        );

        jtap.addTab("Añadir Actividades ", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Projectos");
        jt_activs.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_activs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_activsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_activs);

        olawenas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                olawenasItemStateChanged(evt);
            }
        });
        olawenas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olawenasMouseClicked(evt);
            }
        });

        jLabel15.setText("Projectos");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("Visualizar Projectos");

        jButton7.setText("Modificar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(olawenas, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(336, 336, 336)
                                .addComponent(jButton7)))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(olawenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton7)
                .addContainerGap())
        );

        jtap.addTab("Projectos Creados", jPanel2);

        jScrollPane4.setViewportView(jTable1);

        jButton4.setText("Ejecutar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Ejecutar Actividades");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(wombo_hilo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(wombo_hilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jtap.addTab("Ejecutar Actividad", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtap)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtap)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String f = wombo_tipo.getSelectedItem().toString();
        if (f.equals("Sucesora")) {
            try {
                String nombre = tf_nombre.getText();
                int duracion = (int) sp_duracion.getValue();
                int posibilidad = (int) sp_posibilidad_retraso.getValue();
                actividades_sucesoras.add(new Actividades(nombre, duracion, posibilidad, f));
                JOptionPane.showMessageDialog(this, "Actividad Sucesora creada Correctamente");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hubo un error al crear la Actividad");
            }

        } else if (f.equals("Principal")) {
            try {
                String s = wombo_projecto.getSelectedItem().toString();
                if (s.length() > 0) {
                    String nombre = tf_nombre.getText();
                    int duracion = (int) sp_duracion.getValue();
                    int posibilidad = (int) sp_posibilidad_retraso.getValue();
                    actividades_principales.add(new Actividades(nombre, duracion, posibilidad, f));
                    int pos = -1;
                    for (int i = 0; i < projects.size(); i++) {
                        if (projects.get(i).getNombre().equals(s)) {
                            pos = i;
                        }
                    }
                    Actividades sexo = new Actividades(nombre, duracion, posibilidad, f);
                    ArrayList<Actividades> ola = new ArrayList<>();
                    ArrayList<Actividades> ola2 = new ArrayList<>();
                    sexo.setActividades_sucesoras(ola);
                    sexo.setActividades_predecesoras(ola2);
                    projects.get(pos).getActividades().add(sexo);
                    JOptionPane.showMessageDialog(this, "Actividad Principal creada Correctamente");
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Hubo un error al crear la Actividad");
            }

        } else {
            try {
                String nombre = tf_nombre.getText();
                int duracion = (int) sp_duracion.getValue();
                int posibilidad = (int) sp_posibilidad_retraso.getValue();
                actividades_predecesoras.add(new Actividades(nombre, duracion, posibilidad, f));
                JOptionPane.showMessageDialog(this, "Actividad Predecesora creada Correctamente");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hubo un error al crear la Actividad");
            }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nombre = tf_nombre_projecto.getText();
        int auz = 0;
        for (int i = 0; i < projects.size(); i++) {
            if (projects.get(i).getNombre().equals(nombre)) {
                auz = 1;
            }
        }
        if (auz == 0) {
            Projectos p = new Projectos(nombre);
            ArrayList<Actividades> ola = new ArrayList<>();
            p.setActividades(ola);
            projects.add(p);
            DefaultComboBoxModel m = (DefaultComboBoxModel) wombo_projecto.getModel();
            m.addElement(new Projectos(nombre));
            wombo_projecto.setModel(m);
        } else {
            JOptionPane.showMessageDialog(this, "Un projecto no puede tener el mismo nombre");
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jtapStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtapStateChanged
        // TODO add your handling code here:
        if (jtap.getSelectedIndex() == 1) {
            DefaultComboBoxModel m = (DefaultComboBoxModel) wombo_projecto.getModel();
            DefaultComboBoxModel m2 = (DefaultComboBoxModel) projectos.getModel();
            DefaultComboBoxModel m23 = (DefaultComboBoxModel) olawenas.getModel();
            DefaultComboBoxModel m233 = (DefaultComboBoxModel) wombo_hilo.getModel();
            m2.removeAllElements();
            m.removeAllElements();
            m23.removeAllElements();
            m233.removeAllElements();
            for (int i = 0; i < projects.size(); i++) {
                m.addElement(projects.get(i));
                m2.addElement(projects.get(i));
                m23.addElement(projects.get(i));
                m233.addElement(projects.get(i));
            }
            olawenas.setModel(m23);
            projectos.setModel(m2);
            wombo_projecto.setModel(m);
            wombo_hilo.setModel(m233);

            DefaultListModel modelolista = (DefaultListModel) jl_sucesoras.getModel();
            modelolista.removeAllElements();

            DefaultListModel modelolista2 = (DefaultListModel) jl_predecesoras.getModel();
            modelolista2.removeAllElements();
            for (int i = 0; i < actividades_sucesoras.size(); i++) {
                modelolista.addElement(actividades_sucesoras.get(i));

            }
            for (int i = 0; i < actividades_predecesoras.size(); i++) {
                modelolista2.addElement(actividades_predecesoras.get(i));
            }
            jl_predecesoras.setModel(modelolista2);
            jl_sucesoras.setModel(modelolista);
        } else if (jtap.getSelectedIndex() == 3) {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Nombre");
            modelo.addColumn("Inicio Temprano");
            modelo.addColumn("Duracion");
            modelo.addColumn("Final Temprano");
            modelo.addColumn("Retraso");
            //  modelo.addColumn("Estado");
            jTable1.setModel(modelo);

            /* DefaultTreeModel modelo = (DefaultTreeModel) jt_activs.getModel();//porque el ()
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
            raiz.removeAllChildren();
            for (int i = 0; i < projects.size(); i++) {
                DefaultMutableTreeNode projecto = new DefaultMutableTreeNode(projects.get(i));
                for (int j = 0; j < projects.get(i).getActividades().size(); j++) {
                    DefaultMutableTreeNode principal = new DefaultMutableTreeNode(projects.get(i).getActividades().get(j));
                    DefaultMutableTreeNode prede = new DefaultMutableTreeNode("Predecesoras");
                    DefaultMutableTreeNode susesoras = new DefaultMutableTreeNode("Susesoras");
                    for (int k = 0; k < projects.get(i).getActividades().get(j).getActividades_sucesoras().size(); k++) {
                        susesoras.add(new DefaultMutableTreeNode(projects.get(i).getActividades().get(j).getActividades_sucesoras().get(k)));
                    }
                    for (int k2 = 0; k2 < projects.get(i).getActividades().get(j).getActividades_predecesoras().size(); k2++) {
                        prede.add(new DefaultMutableTreeNode(projects.get(i).getActividades().get(j).getActividades_predecesoras().get(k2)));
                    }
                    principal.add(prede);
                    principal.add(susesoras);
                    projecto.add(principal);
                }
                raiz.add(projecto);

            }
            modelo.reload();
             */
        }
    }//GEN-LAST:event_jtapStateChanged

    private void projectosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_projectosItemStateChanged
        // TODO add your handling code here:
        temp = (Projectos) projectos.getSelectedItem();

        if (temp != null) {
            DefaultComboBoxModel m = (DefaultComboBoxModel) actividad_predecesoras.getModel();
            m.removeAllElements();
            for (int i = 0; i < temp.getActividades().size(); i++) {
                m.addElement(temp.getActividades().get(i));
            }
            actividad_predecesoras.setModel(m);
        }
    }//GEN-LAST:event_projectosItemStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if (jl_sucesoras.getSelectedIndex() >= 0) {// verificar si teiene una persona seleccionada
            DefaultListModel modeloLISTA = (DefaultListModel) jl_sucesoras.getModel();
            DefaultComboBoxModel m = (DefaultComboBoxModel) actividad_predecesoras.getModel();
            DefaultComboBoxModel m2 = (DefaultComboBoxModel) projectos.getModel();
            if (m.getSelectedItem() != null) {
                String prede = m.getSelectedItem().toString();
                String project = m2.getSelectedItem().toString();
                int pos1 = -1;
                int pos2 = -2;
                for (int i = 0; i < projects.size(); i++) {
                    if (projects.get(i).getNombre().equals(project)) {
                        pos1 = i;
                    }
                }
                for (int i = 0; i < temp.getActividades().size(); i++) {
                    if (temp.getActividades().get(i).getNombre().equals(prede)) {
                        pos2 = i;
                    }
                }
                Actividades a = ((Actividades) modeloLISTA.get(jl_sucesoras.getSelectedIndex()));
                System.out.println(temp.getActividades().get(pos2));
                temp.getActividades().get(pos2).getActividades_sucesoras().add(a);
                JOptionPane.showMessageDialog(this, "Actividad Sucesora Agregada Correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Porfavor Seleccione algo");
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if (jl_predecesoras.getSelectedIndex() >= 0) {// verificar si teiene una persona seleccionada
            DefaultListModel modeloLISTA = (DefaultListModel) jl_predecesoras.getModel();
            DefaultComboBoxModel m = (DefaultComboBoxModel) actividad_predecesoras.getModel();
            DefaultComboBoxModel m2 = (DefaultComboBoxModel) projectos.getModel();
            if (m.getSelectedItem() != null) {
                String prede = m.getSelectedItem().toString();
                String project = m2.getSelectedItem().toString();
                int pos1 = -1;
                int pos2 = -2;
                for (int i = 0; i < projects.size(); i++) {
                    if (projects.get(i).getNombre().equals(project)) {
                        pos1 = i;
                    }
                }
                for (int i = 0; i < temp.getActividades().size(); i++) {
                    if (temp.getActividades().get(i).getNombre().equals(prede)) {
                        pos2 = i;
                    }
                }
                Actividades a = ((Actividades) modeloLISTA.get(jl_predecesoras.getSelectedIndex()));
                System.out.println(temp.getActividades().get(pos2));
                temp.getActividades().get(pos2).getActividades_predecesoras().add(a);
                JOptionPane.showMessageDialog(this, "Actividad Predecesora Agregada Correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Porfavor Seleccione algo");
            }
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel m2 = (DefaultComboBoxModel) actividad_predecesoras.getModel();
        Actividades ac = ((Actividades) m2.getSelectedItem());
        if (ac.getActividades_predecesoras().isEmpty()) {
            ac.setInicio_temprano(1);
            ac.setFinal_temprano(ac.getInicio_temprano() + ac.getDuracion());
        } else {
            int mayor = -1;
            for (int i = 0; i < ac.getActividades_predecesoras().size(); i++) {
                for (int j = 0; j < ac.getActividades_predecesoras().size(); j++) {
                    if (ac.getActividades_predecesoras().get(i).getPosibilidad_retraso() > ac.getActividades_predecesoras().get(j).getPosibilidad_retraso()) {
                        mayor = ac.getActividades_predecesoras().get(i).getPosibilidad_retraso();
                    }
                }

            }
            System.out.println(mayor);
            ac.setInicio_temprano(mayor + 1);
            ac.setFinal_temprano(ac.getInicio_temprano() + ac.getDuracion());
        }
        System.out.println("Duracion " + ac.getDuracion());
        System.out.println("Inicio temprano " + ac.getInicio_temprano());
        System.out.println("Final temprano " + ac.getFinal_temprano());
    }//GEN-LAST:event_jButton6MouseClicked

    private void olawenasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olawenasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_olawenasMouseClicked

    private void olawenasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_olawenasItemStateChanged
        // TODO add your handling code here:
        DefaultTreeModel modelo = (DefaultTreeModel) jt_activs.getModel();//porque el ()
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        raiz.removeAllChildren();
        temp = (Projectos) olawenas.getSelectedItem();
        if (temp != null) {
            DefaultComboBoxModel m = (DefaultComboBoxModel) olawenas.getModel();
            index = olawenas.getSelectedIndex();
            for (int i = 0; i < 1; i++) {
                DefaultMutableTreeNode projecto = new DefaultMutableTreeNode(temp.getNombre());
                for (int j = 0; j < temp.getActividades().size(); j++) {
                    DefaultMutableTreeNode principal = new DefaultMutableTreeNode(temp.getActividades().get(j));
                    DefaultMutableTreeNode prede = new DefaultMutableTreeNode("Predecesoras");
                    DefaultMutableTreeNode susesoras = new DefaultMutableTreeNode("Susesoras");
                    for (int k = 0; k < temp.getActividades().get(j).getActividades_sucesoras().size(); k++) {
                        susesoras.add(new DefaultMutableTreeNode(temp.getActividades().get(j).getActividades_sucesoras().get(k)));
                    }
                    for (int k2 = 0; k2 < temp.getActividades().get(j).getActividades_predecesoras().size(); k2++) {
                        prede.add(new DefaultMutableTreeNode(temp.getActividades().get(j).getActividades_predecesoras().get(k2)));
                    }
                    principal.add(prede);
                    principal.add(susesoras);
                    projecto.add(principal);
                }
                raiz.add(projecto);

            }
            modelo.reload();
        }
    }//GEN-LAST:event_olawenasItemStateChanged

    private void jt_activsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_activsMouseClicked

    }//GEN-LAST:event_jt_activsMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        try {

            DefaultTreeModel modelo = (DefaultTreeModel) jt_activs.getModel();//porque el ()
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
            String o = JOptionPane.showInputDialog(this, "Que desea modificar ?\n1) Actividad principal\n2) Actividades Predecesoras\n3) Actividades Sucesoras ");
            int pos = Integer.parseInt(o);
            if (pos == 1) {
                String p = JOptionPane.showInputDialog(this, "Ingrese la nueva duracion de la Actividad Principal");
                int pos2 = Integer.parseInt(p);
                actividad_seleccionado = ((Actividades) ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(0)).getUserObject());
                actividad_seleccionado.setDuracion(pos2);
                if (actividad_seleccionado.getActividades_predecesoras().isEmpty()) {
                    actividad_seleccionado.setInicio_temprano(1);
                    actividad_seleccionado.setFinal_temprano(actividad_seleccionado.getInicio_temprano() + actividad_seleccionado.getDuracion());
                } else {
                    int mayor = actividad_seleccionado.getActividades_predecesoras().get(0).getPosibilidad_retraso();
                    for (int i = 0; i < actividad_seleccionado.getActividades_predecesoras().size(); i++) {
                        for (int j = 0; j < actividad_seleccionado.getActividades_predecesoras().size(); j++) {
                            if (actividad_seleccionado.getActividades_predecesoras().get(i).getPosibilidad_retraso() > actividad_seleccionado.getActividades_predecesoras().get(j).getPosibilidad_retraso()) {
                                mayor = actividad_seleccionado.getActividades_predecesoras().get(i).getPosibilidad_retraso();
                            }
                        }

                    }
                    System.out.println("maynor " + mayor);
                    actividad_seleccionado.setInicio_temprano(mayor + 1);
                    actividad_seleccionado.setFinal_temprano(actividad_seleccionado.getInicio_temprano() + actividad_seleccionado.getDuracion());
                    actividades_principales.remove(index);
                    actividades_principales.add(actividad_seleccionado);
                }
                System.out.println("Duracion " + actividad_seleccionado.getDuracion());
                System.out.println("Inicio temprano " + actividad_seleccionado.getInicio_temprano());
                System.out.println("Final temprano " + actividad_seleccionado.getFinal_temprano());
                System.out.println(actividades_principales);
            } else if (pos == 2) {
                String p = JOptionPane.showInputDialog(this, "Ingrese la posicion de la actividad que desea modificar");
                int pos2 = Integer.parseInt(p);
                String p4 = JOptionPane.showInputDialog(this, "Ingrese la posicion de la Predecesora que desea modificar");
                int pos24 = Integer.parseInt(p4);
                actividad_seleccionado = ((Actividades) ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(pos2).getChildAt(0).getChildAt(pos24)).getUserObject());
                String p2 = JOptionPane.showInputDialog(this, "Ingrese la nueva Duracion de la actividad PREDECESORA");
                int pos22 = Integer.parseInt(p2);
                actividad_seleccionado.setDuracion(pos22);
                int sex=olawenas.getSelectedIndex();
                System.out.println("nodo "+actividad_seleccionado);
            } else if (pos == 3) {
                String p = JOptionPane.showInputDialog(this, "Ingrese la posicion de la actividad que desea modificar");
                int pos2 = Integer.parseInt(p);
                String p4 = JOptionPane.showInputDialog(this, "Ingrese la posicion de la sucesora que desea modificar");
                int pos24 = Integer.parseInt(p4);
                actividad_seleccionado = ((Actividades) ((DefaultMutableTreeNode) raiz.getChildAt(0).getChildAt(pos2).getChildAt(pos24)).getUserObject());                       
                String p2 = JOptionPane.showInputDialog(this, "Ingrese la nueva Duracion de la actividad SUCESORA");
                int pos22 = Integer.parseInt(p2);
                actividad_seleccionado.setDuracion(pos22);
                System.out.println("nodo "+actividad_seleccionado);
            } else {
                JOptionPane.showMessageDialog(this, "Dato no Valido!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese DAtos Validos");
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.out.println("EJECUTA");
        int pos = wombo_hilo.getSelectedIndex();
        int t = 0;
        ArrayList<Actividades> ordenadas = new ArrayList<>();
        for (int i = 0; i < projects.get(pos).getActividades().size(); i++) {

            ordenadas.add(projects.get(pos).getActividades().get(i));
            for (int j = 0; j < projects.get(pos).getActividades().get(i).getActividades_predecesoras().size(); j++) {
                ordenadas.add(projects.get(pos).getActividades().get(i).getActividades_predecesoras().get(j));
            }
            for (int j = 0; j < projects.get(pos).getActividades().get(i).getActividades_sucesoras().size(); j++) {
                ordenadas.add(projects.get(pos).getActividades().get(i).getActividades_sucesoras().get(j));
            }
        }
        hilo_actividad = new Hilo_actividades();
        hilo_actividad.setLista(ordenadas);
        hilo_actividad.setTabla(jTable1);
        hilo_actividad.start();

        if (pos >= 0) {

        }
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(princi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(princi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(princi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(princi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new princi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> actividad_predecesoras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> jl_predecesoras;
    private javax.swing.JList<String> jl_sucesoras;
    private javax.swing.JTree jt_activs;
    private javax.swing.JTabbedPane jtap;
    private javax.swing.JComboBox<String> olawenas;
    private javax.swing.JComboBox<String> projectos;
    private javax.swing.JSpinner sp_duracion;
    private javax.swing.JSpinner sp_posibilidad_retraso;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre_projecto;
    private javax.swing.JPanel uno;
    private javax.swing.JComboBox<String> wombo_hilo;
    private javax.swing.JComboBox<String> wombo_projecto;
    private javax.swing.JComboBox<String> wombo_tipo;
    // End of variables declaration//GEN-END:variables
    DefaultMutableTreeNode nodo_seleccionado2;
    ArrayList<Projectos> projects = new ArrayList();
    ArrayList<Actividades> actividades_principales = new ArrayList();
    ArrayList<Actividades> actividades_sucesoras = new ArrayList();
    ArrayList<Actividades> actividades_predecesoras = new ArrayList();
    Projectos temp;
    Actividades actividad_seleccionado;
    int index = 0;
    Hilo_actividades hilo_actividad;
}
